variable "realm_id" {
  type        = string
  description = <<-EOM
  The realm this client is attached to.
  EOM
}

variable "enabled" {
  type        = string
  description = <<-EOM
  When false, this client will not be able to initiate a login or obtain access
  tokens. Defaults to true.
  EOM

  default = true
}

variable "name" {
  type        = string
  description = <<-EOM
  The display name of this client in the GUI.
  EOM

  default = ""
}

variable "client_id" {
  type        = string
  description = <<-EOM
  The Client ID for this client, referenced in the URI during authentication and
  in issued tokens.
  EOM
}

variable "description" {
  type        = string
  description = <<-EOM
  The description of this client in the GUI.
  EOM

  default = ""
}

variable "access_type" {
  type        = string
  description = <<-EOM
  Required, Specifies the type of client, which can be one of the following:
  * `CONFIDENTIAL`: Used for server-side clients that require both client ID and
    secret when authenticating. This client should be used for applications
    using the Authorization Code or Client Credentials grant flows.
  * `PUBLIC`: Used for browser-only applications that do not require a client
    secret, and instead rely only on authorized redirect URIs for security. This
    client should be used for applications using the Implicit grant flow.
  * `BEARER-ONLY`: Used for services that never initiate a login. This client
    will only allow bearer token requests.
  EOM

  default = "CONFIDENTIAL"
}

variable "client_secret" {
  type        = string
  description = <<-EOM
  The secret for clients with an access_type of CONFIDENTIAL or BEARER-ONLY.
  This value is sensitive and should be treated with the same care as a
  password. If omitted, this will be generated by Keycloak.
  EOM

  sensitive = true
  default   = null
}

variable "client_secret_wo" {
  type        = string
  description = <<-EOM
  Write-Only, the secret for clients with an access_type of CONFIDENTIAL or
  BEARER-ONLY. This is a write-only argument and Terraform does not store them
  in state or plan files. If omitted, this will fallback to use client_secret.
  EOM

  sensitive = true
  default   = null
}

variable "client_secret_wo_version" {
  type        = number
  description = <<-EOM
  Functions as a flag and/or trigger to indicate Terraform when to use the input
  value in client_secret_wo to execute a Create or Update operation. The value
  of this argument is stored in the state and plan files. Required when using
  client_secret_wo.
  EOM

  default = null
}

variable "client_secret_regenerate_when_changed" {
  type        = map(string)
  description = <<-EOM
  Arbitrary map of values that, when changed, will trigger rotation of the
  secret.
  NOTE! Conflicts with client_secret, client_secret_wo and
  client_secret_wo_version attribute and can't be used together
  EOM

  default = {}
}

variable "client_authenticator_type" {
  type        = string
  description = <<-EOM
  Defaults to client-secret. The authenticator type for clients with an access_type of CONFIDENTIAL or BEARER-ONLY. A default Keycloak installation will have the following available types:
  * `client-secret`: (Default) Use client id and client secret to authenticate
    client.
  * `client-jwt`: Use signed JWT to authenticate client. Set signing algorithm in
    extra_config with attributes.token.endpoint.auth.signing.alg = <alg>
  * `client-x509`: Use x509 certificate to authenticate client. Set Subject DN in
    extra_config with attributes.x509.subjectdn = <subjectDn>
  * `client-secret-jwt`: Use signed JWT with client secret to authenticate
    client. Set signing algorithm in extra_config with
    attributes.token.endpoint.auth.signing.alg = <alg>
  EOM

  nullable = false
  default  = "client-secret"
}
#
variable "standard_flow_enabled" {
  type        = bool
  description = <<-EOM
  When true, the OAuth2 Authorization Code Grant will be enabled for this
  client.
  EOM

  nullable = false
  default  = false
}

variable "implicit_flow_enabled" {
  type        = bool
  description = <<-EOM
  When true, the OAuth2 Implicit Grant will be enabled for this client.
  EOM

  nullable = false
  default  = false
}

variable "direct_access_grants_enabled" {
  type        = bool
  description = <<-EOM
  When true, the OAuth2 Resource Owner Password Grant will be enabled for this
  client.
  EOM

  nullable = false
  default  = false
}

variable "service_accounts_enabled" {
  type        = bool
  description = <<-EOM
  When true, the OAuth2 Client Credentials grant will be enabled for this
  client.
  EOM

  default = false
}

variable "frontchannel_logout_enabled" {
  type        = bool
  description = <<-EOM
  When true, frontchannel logout will be enabled for this client. Specify the
  url with frontchannel_logout_url.
  EOM

  default = false
}

variable "frontchannel_logout_url" {
  type        = string
  description = <<-EOM
  Optional, The frontchannel logout url.
  This is applicable only when frontchannel_logout_enabled is true.
  EOM

  default = ""
}

variable "valid_redirect_uris" {
  type        = list(string)
  description = <<-EOM
  A list of valid URIs a browser is permitted to redirect to after a successful
  login or logout. Simple wildcards in the form of an asterisk can be used here.
  This attribute must be set if either standard_flow_enabled or
  implicit_flow_enabled is set to true.
  EOM

  default = []
}

variable "valid_post_logout_redirect_uris" {
  type        = list(string)
  description = <<-EOM
  A list of valid URIs a browser is permitted to redirect to after a successful
  logout.
  EOM

  nullable = false
  default  = []
}

variable "web_origins" {
  type        = list(string)
  description = <<-EOM
  A list of allowed CORS origins. To permit all valid redirect URIs, add +. Note
  that this will not include the * wildcard. To permit all origins, explicitly
  add *.
  EOM

  nullable = false
  default  = []
}

variable "root_url" {
  type        = string
  description = <<-EOM
  When specified, this URL is prepended to any relative URLs found within
  valid_redirect_uris, web_origins, and admin_url. NOTE: Due to limitations in
  the Keycloak API, when the root_url attribute is used, the
  valid_redirect_uris, web_origins, and admin_url attributes will be required.
  EOM

  default = ""
}

variable "admin_url" {
  type        = string
  description = <<-EOM
  URL to the admin interface of the client.
  EOM

  default = ""
}

variable "base_url" {
  type        = string
  description = <<-EOM
  Default URL to use when the auth server needs to redirect or link back to the client.
  EOM

  default = ""
}

variable "pkce_code_challenge_method" {
  type        = string
  description = <<-EOM
  The challenge method to use for Proof Key for Code Exchange. Can be either
  plain or S256 or set to empty value ``.
  EOM

  nullable = false
  default  = ""
}

variable "require_dpop_bound_tokens" {
  type        = bool
  description = <<-EOM
  Enable support for Demonstrating Proof-of-Possession (DPoP, bound tokens).
  EOM

  default = false
}

variable "full_scope_allowed" {
  type        = bool
  description = <<-EOM
  Allow to include all roles mappings in the access token.
  EOM

  default = true
}

variable "access_token_lifespan" {
  type        = string
  description = <<-EOM
  The amount of time in seconds before an access token expires. This will
  override the default for the realm.
  EOM

  default = ""
}
#
variable "client_offline_session_idle_timeout" {
  type        = string
  description = <<-EOM
  Time a client session is allowed to be idle before it expires. Tokens are
  invalidated when a client session is expired. If not set it uses the standard
  SSO Session Idle value.
  EOM

  default = ""
}
#
variable "client_offline_session_max_lifespan" {
  type        = string
  description = <<-EOM
  Max time before a client session is expired. Tokens are invalidated when a
  client session is expired. If not set, it uses the standard SSO Session Max
  value.
  EOM

  default = ""
}
#
variable "client_session_idle_timeout" {
  type        = string
  description = <<-EOM
  Time a client offline session is allowed to be idle before it expires. Offline
  tokens are invalidated when a client offline session is expired. If not set it
  uses the Offline Session Idle value.
  EOM

  default = ""
}
#
variable "client_session_max_lifespan" {
  type        = string
  description = <<-EOM
  Max time before a client offline session is expired. Offline tokens are
  invalidated when a client offline session is expired. If not set, it uses the
  Offline Session Max value.
  EOM

  default = ""
}

variable "consent_required" {
  type        = bool
  description = <<-EOM
  When true, users have to consent to client access.
  EOM

  default = true
}

variable "display_on_consent_screen" {
  type        = bool
  description = <<-EOM
  When true, the consent screen will display information about the client
  itself.
  This is applicable only when consent_required is true.
  EOM

  default = true
}

variable "consent_screen_text" {
  type        = string
  description = <<-EOM
  The text to display on the consent screen about permissions specific to this
  client.
  This is applicable only when display_on_consent_screen is true.
  EOM

  default = ""
}

variable "login_theme" {
  type        = string
  description = <<-EOM
  The client login theme. This will override the default theme for the realm.
  EOM

  default = ""
}

variable "exclude_session_state_from_auth_response" {
  type        = bool
  description = <<-EOM
  When true, the parameter session_state will not be included in OpenID Connect
  Authentication Response.
  EOM

  default = false
}

variable "exclude_issuer_from_auth_response" {
  type        = bool
  description = <<-EOM
  When true, the parameter iss will not be included in OpenID Connect
  Authentication Response.
  EOM

  default = null
}

variable "use_refresh_tokens" {
  type        = bool
  description = <<-EOM
  If this is true, a refresh_token will be created and added to the token
  response. If this is false then no refresh_token will be generated.
  EOM

  default = true
}

variable "use_refresh_tokens_client_credentials" {
  type        = string
  description = <<-EOM
  If this is true, a refresh_token will be created and added to the token
  response if the client_credentials grant is used and a user session will be
  created. If this is false then no refresh_token will be generated and the
  associated user session will be removed, in accordance with OAuth 2.0 RFC6749
  Section 4.4.3.
  EOM

  default = false
}

variable "standard_token_exchange_enabled" {
  type        = bool
  description = <<-EOM
  Enables support for Standard Token Exchange
  EOM

  default = false
}

variable "allow_refresh_token_in_standard_token_exchange" {
  type        = string
  description = <<-EOM
  Defines whether to allow refresh token in Standard Token Exchange. Possible
  values are NO (default), and SAME_SESSION.
  EOM

  default = "NO"
}

variable "oauth2_device_authorization_grant_enabled" {
  type        = bool
  description = <<-EOM
  Enables support for OAuth 2.0 Device Authorization Grant, which means that
  client is an application on device that has limited input capabilities or lack
  a suitable browser.
  EOM

  default = null
}

variable "oauth2_device_code_lifespan" {
  type        = string
  description = <<-EOM
  The maximum amount of time a client has to finish the device code flow before
  it expires.
  EOM

  default = ""
}

variable "oauth2_device_polling_interval" {
  type        = string
  description = <<-EOM
  The minimum amount of time in seconds that the client should wait between
  polling requests to the token endpoint.
  EOM

  default = ""
}

variable "backchannel_logout_url" {
  type        = string
  description = <<-EOM
  The URL that will cause the client to log itself out when a logout request is
  sent to this realm.
  If omitted, no logout request will be sent to the client is this case.
  EOM

  default = ""
}
#
variable "backchannel_logout_session_required" {
  type        = bool
  description = <<-EOM
  When true, a sid (session ID), claim will be included in the logout token when
  the backchannel logout URL is used.
  EOM

  default = true
}

variable "backchannel_logout_revoke_offline_sessions" {
  type        = bool
  description = <<-EOM
  Specifying whether a "revoke_offline_access" event is included in the Logout
  Token when the Backchannel Logout URL is used. Keycloak will revoke offline
  sessions when receiving a Logout Token with this event.
  EOM

  default = false
}

variable "always_display_in_console" {
  type        = bool
  description = <<-EOM
  Always list this client in the Account UI, even if the user does not have an
  active session.
  EOM

  default = false
}

variable "extra_config" {
  type        = map(string)
  description = <<-EOM
  A map of key/value pairs to add extra configuration attributes to this client.
  This can be used for custom attributes, or to add configuration attributes
  that are not yet supported by this Terraform provider.

  Use this attribute at your own risk, as it may conflict with top-level
  configuration attributes in future provider updates.

  For example, the extra_config map can be used to set Authentication Context
  Class Reference (ACR) to Level of Authentication (LoA), mapping
  EOM

  nullable = false
  default  = {}
}

variable "import" {
  type        = bool
  description = <<-EOM
  When true, the client with the specified client_id is assumed to already
  exist, and it will be imported into state instead of being created.
  This attribute is useful when dealing with clients that Keycloak creates
  automatically during realm creation, such as account and admin-cli.
  Note, that the client will not be removed during destruction if import is true.
  EOM

  nullable = false
  default  = false
}

variable "default_scopes" {
  type        = list(string)
  description = <<-EOM
  An array of default client scope names to attach to this client.
  EOM

  default = []
}

variable "optional_scopes" {
  type        = list(string)
  description = <<-EOM
  An array of client scope names to attach to this client as optional scopes.
  EOM

  default = []
}

variable "realm_roles" {
  type        = set(string)
  description = <<-EOM
  A set of realm role names to assign to the service account user of this client.
  This is applicable only when service_accounts_enabled is true.
  EOM

  nullable = false
  default  = []

}
